
[theme]
name = "Rice"

[settings_window]
background_color = "#1e1e2e"
font_color = "#cdd6f4"
accent_color = "#cba6f7"
border_color = "#313244"
corner_radius = 12

[dock]
# padding order [left, top, right, bottom]
# corner order [top_left, top_right, bottom_left, bottom_right]

frame_padding = [15, 10, 15, 10]
frame_corner_radius = [10, 10, 10, 10]
icon_corner_radius = [10, 10, 10, 10]

frame_border_width = 2
icon_border_width = 0
icon_size = 56
icon_margine = 8
dock_item_spacing = 10

active_indicator_height_on_focus = 6
active_indicator_height_on_background = 8
active_indicator_width_on_focus = 16
active_indicator_width_on_background = 8
spacing_between_icon_and_indicator = 8

icon_frame_shadow_blur_radius = 20
icon_frame_shadow_color = [0, 0, 0, 125]
icon_frame_shadow_offset = [0, 0]

frame_background_color = "#45475a"
icon_background_color = "#1e1e2e"
font_color = "#cdd6f4"
p_accent_color = "#cba6f7"
s_accent_color = "#69587e"
frame_border_color = "#7f849c"
icon_border_color = "transparent"
